### ISSUE TITLE
Why not only use the websockets for all CRUD?

### ISSUE THREAD

**Issue by qinshulei** [g00glen00b/spring-websockets#1]
Hi.
It seems that the project  not only use the websockets but also the REST for create and delete.Why not only use the websockets for all CRUD?

**Comment by g00glen00b** [comment]
Quoting my blogpost:

> This isn’t a “pure” WebSockets application, but uses WebSockets to notify each client. You can choose for this hybrid setup, or you can choose to persist model changes through WebSockets as well, however, this is not fully integrated into AngularJS (not on the same level RESTful webservice are), so it means the project setup will take quite longer.

So, the main reason why I used REST for persistence is for convenience. Not only the AngularJS part would take significantly longer, the back-end would take longer as well. Knowing that you could easiliy expose REST services for CRUD operations using frameworks like spring-data-jpa or even spring-data-rest (which would take away the work necessary for setting up a controller).

I'm also using this approach at a customer for another reason as well. They do not entirely trust websockets yet, or at least not at the same level as they do trust RESTful webservices. Their requirement was that the websockets should not take too long to implement and removing them should not take much time either.
That's why I chose to develop an application using WebSockets only to send a notification at which the client can decide whether or not to retrieve the latest data using REST.

**Comment by qinshulei** [comment]
Thank you.
